
name: Linux

on:
  push:
    branches: [ main, doc ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: install dependency
      run: |
        sudo apt update
        sudo apt-get update
        sudo apt-get -qy install build-essential zlib1g zlib1g-dev curl libcurl4-openssl-dev lzma-dev liblzma-dev libeigen3-dev

    - name: install htslib
      run: |
        git clone --recursive https://github.com/samtools/htslib.git
        cd htslib && autoreconf -i && ./configure --enable-libcurl
        sudo make -j6 install
        sudo ldconfig
        cd -

    - name: unit test
      run: |
        cd test
        # export ASAN_OPTIONS=alloc_dealloc_mismatch=0
        make
        make test
        # find . -name "*.bin" -exec '{}' --success ';'

    - name: tools test
      run: |
        cd tools
        make -j6
        make test
