name: MacOS

on:
  push:
    branches: [ main, doc ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: install dependency
      run: |
        brew install htslib eigen

    - name: test
      run: |
        cd test
        export LIBRARY_PATH=${LIBRARY_PATH}:$(brew --prefix)/lib
        export C_INCLUDE_PATH=${C_INCLUDE_PATH}:$(brew --prefix)/include
        export CPPFLAGS=-I"$(brew --prefix)/include"
        make HTSINC=$(brew --prefix)/include HTSLIB=$(brew --prefix)/lib
        make test
